name: ffs_v3
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - h5py
  - datasets
  - python-dotenv
  - cudatoolkit=11.8
  - tqdm
  - pillow
  - protobuf
  - pip:
      - opencv-python
      - transformers
      - sentencepiece
      - requests
      - pyyaml
      - huggingface-hub
